apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-server
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1  
  template:
    metadata:
      labels:
        app: app-server
    spec:
      containers:
        - name: app-server
          image: gcr.io/PROJECT_ID/IMAGE:TAG    